[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
tradium = "9cmTderZ6Sthr4UYNvc3sdLyZDDw5fnzed2PtnyP4ZF7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Desktop/Deployment_Ready/wallets/Admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
